import type { Job } from '../data/jobs';
import { calculateMatchScore } from './matching';
import type { Preferences } from './matching';

export interface Digest {
    date: string;
    jobs: {
        job: Job;
        matchScore: number;
    }[];
}

const DIGEST_STORAGE_PREFIX = 'jobTrackerDigest_';

export const getTodayDateString = (): string => {
    return new Date().toISOString().split('T')[0];
};

export const getExistingDigest = (date: string): Digest | null => {
    const key = `${DIGEST_STORAGE_PREFIX}${date}`;
    const stored = localStorage.getItem(key);
    if (stored) {
        return JSON.parse(stored);
    }
    return null;
};

export const generateDigest = (
    allJobs: Job[],
    prefs: Preferences
): Digest => {
    const today = getTodayDateString();

    // 1. Score all jobs
    const scoredJobs = allJobs.map(job => ({
        job,
        matchScore: calculateMatchScore(job, prefs)
    }));

    // 2. Filter matches (optional: strict cutoff? Requirement says "top 10", implies sorting first)
    // Let's filter out very low scores (e.g. 0) just in case, but requirement says "No matching roles" handling is needed.
    // We'll keep all > 0 for now to find top 10.

    // 3. Sort: Match Score (desc) -> Posted Days Ago (asc)
    scoredJobs.sort((a, b) => {
        if (b.matchScore !== a.matchScore) {
            return b.matchScore - a.matchScore;
        }
        return a.job.postedDaysAgo - b.job.postedDaysAgo;
    });

    // 4. Take top 10
    const topJobs = scoredJobs.slice(0, 10);

    const digest: Digest = {
        date: today,
        jobs: topJobs
    };

    // 5. Persist
    localStorage.setItem(`${DIGEST_STORAGE_PREFIX}${today}`, JSON.stringify(digest));

    return digest;
};

export const formatDigestForClipboard = (digest: Digest): string => {
    let text = `My 9AM Job Digest - ${digest.date}\n\n`;

    digest.jobs.forEach((item, index) => {
        const { job, matchScore } = item;
        text += `${index + 1}. ${job.title} at ${job.company}\n`;
        text += `   Location: ${job.location} | Exp: ${job.experience}\n`;
        text += `   Match: ${matchScore}% | Link: ${job.applyUrl}\n\n`;
    });

    text += `Generated by Job Notification Tracker`;
    return text;
};
